### ISSUE TITLE
プロジェクトのβ版

### ISSUE THREAD

**Issue by masatakashida** [gkumi5638/postphoto#23]
このプロジェクトのβ版をネット上に発表するのはいつ頃にしますか？

**Comment by gkumi5638** [comment]
そうですね。
初めてで、どのくらいかかるものか検討がつかないのが正直な所です。
目安としてはどのくらいかかるものでしょうか。

**Comment by masatakashida** [comment]
ゆっくりやれば３月くらい？
最速で今週末に出すことも可能って感じですね笑
適当な予定を出してもらえると嬉しいです！イメージのリリースを！
それか期日を決めずにゆったりやるのもありかと！

**Comment by gkumi5638** [comment]
今週末、体験してみたいですが、、笑
まずは、3月目標でお願いします!
ありがとうございます！
