### ISSUE TITLE
ページデザイン

### ISSUE THREAD

**Issue by masatakashida** [gkumi5638/postphoto#7]
とりあえず、ページの簡単なデザインを決めたいです。

**Comment by gkumi5638** [comment]
気象現象(空)を投稿するサイトにしたいと思っています。
　日本→現在の空を可視化するもの
　世界→世界の空を見たい。
SNS機能もいずれは追加したい。
◎初めは誰でも空を投稿できるサイトから作成。

**Comment by masatakashida** [comment]
◎初めは誰でも空を投稿できるサイトから作成。
では、はじめは
写真投稿できて、一覧でみられるサイトにしますか！

**Comment by masatakashida** [comment]
https://github.com/carrierwaveuploader/carrierwave
これ使いますか

**Comment by gkumi5638** [comment]
写真投稿を一覧で見られるサイトを作成で！
carrierwave使用で。(他を使ったことがないです)
